name: Push OTA & Release

on:
  push:
    branches:
      - main

jobs:
  push-ota:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload OTA to Server
        run: |
          curl -X POST http://115.29.169.60/push_ota_to_global \
               -F "file=@./image/update.zip.update"

      - name: Get commit info
        id: gitinfo
        run: |
          SHORT_COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date +%Y%m%d)
          echo "COMMIT_SHORT=$SHORT_COMMIT" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "RELEASE_TAG=v1.0.2-$SHORT_COMMIT-$DATE" >> $GITHUB_ENV
          echo "RELEASE_NAME=Release 1.0.2-$SHORT_COMMIT-$DATE" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload update.zip.update to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: ./image/update.zip.update
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
